spring.application.name=treasurer

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nss_treasurer
spring.datasource.username=postgres
spring.datasource.password=saumyanichat__2005
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Clerk Configuration (Custom)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://careful-kite-39.clerk.accounts.dev/.well-known/jwks.json
clerk.api.key=sk_test_e448zopAOCvTX5hgC4mgAugAk9kq7iIazouuKEFUvN

# Gemini API Key
spring.ai.google.gemini.api-key=AIzaSyAzfJ1AynmMqgyoLkU_X6BpBOIkLGmejpM

# Resend Email Configuration
resend.api.key=re_YqRHte8H_7jWKSQEzX3zPhz4TDSR5w5bR
resend.from.email=onboarding@resend.dev

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



